/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.app;

public class Library {
    public static boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args){
        System.out.println(someLibraryMethod());
    }
}
